# Generated by Django 4.1 on 2024-10-26 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('price_per_night', models.DecimalField(decimal_places=2, max_digits=10)),
                ('availability', models.BooleanField(default=True)),
                ('accommodation_type', models.CharField(choices=[('hotel', 'Hotel'), ('rental', 'Rental House')], max_length=10)),
                ('num_rooms', models.IntegerField()),
                ('has_wifi', models.BooleanField(default=True)),
                ('has_pool', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RentalHouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('price_per_night', models.DecimalField(decimal_places=2, max_digits=10)),
                ('availability', models.BooleanField(default=True)),
                ('accommodation_type', models.CharField(choices=[('hotel', 'Hotel'), ('rental', 'Rental House')], max_length=10)),
                ('num_bedrooms', models.IntegerField()),
                ('has_kitchen', models.BooleanField(default=True)),
                ('has_garage', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
