# Generated by Django 4.1 on 2024-10-26 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accommodations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='hotel_photos/'),
        ),
        migrations.AddField(
            model_name='rentalhouse',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='rental_photos/'),
        ),
    ]
