# Generated by Django 4.1 on 2024-10-26 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accommodations', '0003_reservation'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Reservation',
            new_name='Reservation_Accommodation',
        ),
    ]
