# Generated by Django 4.1 on 2024-10-29 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accommodations', '0005_reservation_accommodation_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation_accommodation',
            name='accommodation_type',
            field=models.CharField(default='Hotel', max_length=10),
            preserve_default=False,
        ),
    ]
