# Generated by Django 4.1 on 2024-10-29 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accommodations', '0006_reservation_accommodation_accommodation_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='rentalhouse',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
