# Generated by Django 4.1 on 2024-10-29 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accommodations', '0007_hotel_phone_rentalhouse_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation_accommodation',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
