# Generated by Django 4.1 on 2024-10-29 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accommodations', '0008_reservation_accommodation_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation_accommodation',
            name='reservation_date',
        ),
        migrations.AddField(
            model_name='reservation_accommodation',
            name='end_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='reservation_accommodation',
            name='start_date',
            field=models.DateField(null=True),
        ),
    ]
