# Generated by Django 5.0.6 on 2024-10-29 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accommodations', '0009_remove_reservation_accommodation_reservation_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation_accommodation',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True),
        ),
    ]
